In [1]:
import tensorflow as tf
# from tensorflow.examples.tutorials.mnist import input_data
# mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
import numpy as np
tf.reset_default_graph()

In [2]:
X = np.random.randn(2, 4, 5)
X[1, 1:] = 0

seq_lengths = [4, 1]

cell = tf.contrib.rnn.BasicLSTMCell(
    num_units=3,
    state_is_tuple=True
)
gru = tf.contrib.rnn.GRUCell(3)

W1124 21:26:57.841366 140030004025088 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W1124 21:26:57.842185 140030004025088 deprecation.py:323] From <ipython-input-2-3af4a3cb495d>:8: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
W1124 21:26:57.843462 140030004025088 deprecation.py:323] From <ipython-input-2-3af4a3cb495d>:10: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for u

In [4]:
outputs, last_states = tf.nn.dynamic_rnn(cell, X, seq_lengths, dtype=tf.float64)
gruoutputs, grulast_states = tf.nn.dynamic_rnn(gru, X, seq_lengths, dtype=tf.float64)

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
result, sta, gruout, grusta = sess.run([outputs, last_states, gruoutputs, grulast_states])
print("全序列： \n", result[0])
print("短序列： \n", result[1])
print("LSTM的状态： ", len(sta), "\n", sta[1])
print("GRU的状态： \n", gruout[1])
print("GRU的状态： ", len(grusta), "\n", grusta[1])

W1124 21:34:53.274811 140030004025088 deprecation.py:323] From <ipython-input-4-494b1117aa2d>:1: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W1124 21:34:53.746726 140030004025088 deprecation.py:506] From /home/lx/.local/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W1124 21:34:53.754894 140030004025088 deprecation.py:506] From /home/lx/.local/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py:738: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:


全序列： 
 [[ 0.06800888 -0.1602355   0.01323401]
 [ 0.02395706 -0.14599299  0.1249754 ]
 [-0.27276299 -0.2261432   0.08079311]
 [ 0.07934855 -0.18569386 -0.00625449]]
短序列： 
 [[-0.01687842 -0.16265676 -0.24279819]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
LSTM的状态：  2 
 [[ 0.07934855 -0.18569386 -0.00625449]
 [-0.01687842 -0.16265676 -0.24279819]]
GRU的状态： 
 [[-0.14019825  0.07149118 -0.12245894]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
GRU的状态：  2 
 [-0.14019825  0.07149118 -0.12245894]
